package name.pehl.taoki.security;

import org.restlet.Request;
import org.restlet.Response;
import org.restlet.data.Cookie;
import org.restlet.util.Series;

/**
 * Security check which reads the security token using a configured
 * {@link SecurityTokenReader} and compares it against the security cookie
 * generated by {@link SecurityCookieFilter}.
 * 
 * @author $LastChangedBy:$
 * @version $LastChangedRevision:$
 */
public class CookieSecurityCheck implements SecurityCheck
{
    private final String name;
    private final SecurityTokenReader securityTokenReader;


    public CookieSecurityCheck(@SecurityToken final String name, final SecurityTokenReader securityTokenReader)
    {
        this.name = name;
        this.securityTokenReader = securityTokenReader;
    }


    @Override
    public void check(Request request, Response response) throws SecurityException
    {
        String token = securityTokenReader.readToken(request, response);
        String cookie = readCookie(request);

        String serverName = request.getResourceRef().getHostDomain();
        if (!("localhost".equals(serverName)) && !(token.equals(cookie)))
        {
            throw new SecurityException("Invalid security token");
        }
    }


    private String readCookie(Request request)
    {
        String result = null;
        Series<Cookie> cookies = request.getCookies();
        for (Cookie cookie : cookies)
        {
            if (cookie.getName().equals(name))
            {
                result = cookie.getValue();
                break;
            }
        }
        return result;
    }
}
